# Your project's server will run on localhost:xxxx at this port
URL: "https://sixteenbit.local/squire"

# Gulp will reference these paths when it copies files
PATHS:
  php:
    - "./*.php"
    - "./**/*.php"

  images:
    - "src/img/**/*"

  sass:
    motionui:
      - "node_modules/motion-ui/src"
    foundation:
      - "node_modules/foundation-sites/scss"
    fontawesome:
      - "node_modules/@fortawesome/fontawesome-pro/scss"

  javascript:
    foundation:
      - "node_modules/foundation-sites/dist/js/foundation.js"

    vendors:
      - "node_modules/motion-ui/dist/motion-ui.js"
      - "node_modules/what-input/dist/what-input.js"

    fontawesome:
      - "node_modules/@fortawesome/fontawesome-pro/webfonts/*"

    custom:
      - "src/js/**/_*.js"

  fonts:
    fontawesome:
      - "node_modules/@fortawesome/fontawesome-pro/webfonts/*"

# Used in the theme .pot file for translation
POT:
  domain: 'squire'
  package: 'squire'

# Theme strings used in the `rename` gulp task
THEME:
  ## The current strings in the theme
  CURRENT:
    name: "Squire"
    slug: "squire"
    prefix: "squire_"
    class: "SQ_"
  ## The strings to rename in the theme
  NEW:
    name: "Squire"
    slug: "squire"
    prefix: "squire_"
    class: "SQ_"
